---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Myloo.
--- DateTime: 2022. 09. 25. 20:36
---
---@class Font : Object
Font = Object:extend()
---@param font string
---@param size number
function Font:new(font,size)
    self.path = font or "nil"
    self.size = size or 32
    if self.path ~= "nil" then
        self.font = love.graphics.newFont(font,size)
    else
        self.font = love.graphics.getFont()
    end
end